---
title: "MATH3091: Statistical Modelling II"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    from: markdown+emoji
---

Welcome to the second part of **[MATH3091: Statistical Modelling II]{.attention}**. The first part of the module was taught by Dr Helen Ogden, covering Chapters 1–4 from the lecture notes (see below). This part will focus on **Generalised Linear Models (Chapter 5)** and **Models for Categorical Data (Chapter 6)**.

📖 **Lecture Notes:** [Available here](https://heogden.github.io/math3091/){target="_blank"}

---

### :calendar: **Tentative Schedule**  

Below is the tentative schedule for the second part of the module.   

:::{.small-text}
| Week | Lab   | Session 1 (Thursday) | Session 2 (Friday) | Session 3 (Friday) | Problem sheet |
| ---- | ------- | ---------------- | ----------------- | ----------------- | ------------- |
| 07 | No lab  | 5.1 Exponential family | 5.2 Components of a GLM | 5.3 Examples of GLMs | Sheet 4 |
| 08 | Lab 5   | 5.4 MLE | 5.5 Confidence intervals | PC: sheet 4 | |
| 09 | Lab 6   | 5.6 Comparing GLMs | 5.7 Deviance | 5.8 Models with unknown scale | Sheet 5 |
| 10 | Lab 7   | 6.1 Contingency tables | 6.2 Log-linear models | PC: sheet 5 | |
| 11 | Lab 8   | 6.3 Multinomial sampling | 6.4 Interpretation for two-way tables | 6.5 Interpretation for multiway tables | Sheet 6 |
| 12 | Lab 9  | Revision | Revision | PC: sheet 6 | |
:::