---
title: "Lecture Slides"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    from: markdown+emoji
---

Welcome to the [Lecture Slides]{.attention} section! Here, you will find the slides for each chapter covered in the second part of the module.  

:pushpin: **Note:** slides may be updated throughout the course.

---

### :bar_chart: **Chapter 05: Generalised Linear Models**  
This chapter introduces Generalised Linear Models (GLMs). It covers the exponential family of distributions, key components of a GLM, and examples like logistic regression for binary data and Poisson regression for count data. The chapter also looks at maximum likelihood estimation, confidence intervals, model comparison, scaled deviance, and residual analysis.

- :page_facing_up: [Chapter 5](/slides/_output/chap_5.html) (last updated on 14/04/2025)


### :bar_chart: **Chapter 06: Models for Categorical Data**  
This chapter covers the analysis of categorical data using contingency tables and log-linear models. It also explores multinomial sampling, as well as the interpretation of log-linear models for two-way and multiway tables.

- :page_facing_up: [Chapter 6](/slides/_output/chap_6.html) (last updated on 08/05/2025)
